### ISSUE TITLE
 non-positive interval for NewTicker exception in operator v2.0

### ISSUE THREAD

**Issue by doronl** [PayU/redis-operator#145]
This happen after moving to operator v2.0, two error flows:

flow1:

_⇨ http server started on [::]:8080
I0713 06:31:37.079852       1 request.go:621] Throttling request took 1.030907377s, request: GET:https://172.20.0.1:443/apis/beat.k8s.elastic.co/v1beta1?timeout=32s
{"level":"info","ts":1657693897.833786,"logger":"setup","msg":"Loaded config: {Times:{SyncCheckInterval:0s SyncCheckTimeout:0s SleepDuringTablesAlignProcess:0s ClusterCreateInterval:0s ClusterCreateTimeout:0s ACLFilePropagationDuration:0s ACLFileLoadDuration:0s PodReadyCheckInterval:0s PodReadyCheckTimeout:0s PodNetworkCheckInterval:0s PodNetworkCheckTimeout:0s PodDeleteCheckInterval:0s PodDeleteCheckTimeout:0s RedisPingCheckInterval:0s RedisPingCheckTimeout:0s RedisClusterReplicationCheckInterval:0s RedisClusterReplicationCheckTimeout:0s RedisClusterMeetCheckInterval:0s RedisClusterMeetCheckTimeout:0s RedisManualFailoverCheckInterval:0s RedisManualFailoverCheckTimeout:0s RedisAutoFailoverCheckInterval:0s RedisAutoFailoverCheckTimeout:0s RedisNodesAgreeAboutSlotsConfigTimeout:0s RedisNodesAgreeAboutSlotsConfigCheckInterval:0s RedisRemoveNodeCheckInterval:0s RedisRemoveNodeTimeout:0s WaitForRedisLoadDataSetInMemoryCheckInterval:0s WaitForRedisLoadDataSetInMemoryTimeout:0s SleepIfForgetNodeFails:0s} Thresholds:{SyncMatchThreshold:0 MaxToleratedPodsRecoverAtOnce:0 MaxToleratedPodsUpdateAtOnce:0} Setters:{ExposeSensitiveEntryPoints:false}}"}
{"level":"info","ts":1657693897.8340473,"logger":"setup","msg":"starting manager"}
I0713 06:31:37.834884       1 leaderelection.go:242] attempting to acquire leader lease  redis2/1747e98e.payu.com...
I0713 06:31:58.527891       1 leaderelection.go:252] successfully acquired lease redis2/1747e98e.payu.com
{"level":"info","ts":1657693918.6288643,"logger":"controllers.RedisConfig","msg":"Reconciling operator config for [redis2/redis-memdb-redis-operator]"}
{"level":"info","ts":1657693918.628908,"logger":"controllers.RedisCluster","msg":"Clear all cluster pods..."}
{"level":"info","ts":1657693918.6289356,"logger":"controllers.RedisCluster","msg":"Clear cluster state map..."}
{"level":"info","ts":1657693918.6289468,"logger":"controllers.RedisConfig","msg":"Triggered config reload for [redis2/redis-memdb-redis-operator]"}
{"level":"info","ts":1657693918.6289575,"logger":"controllers.RedisCluster","msg":"Handling initializing cluster..."}
{"level":"info","ts":1657693918.6289678,"logger":"controllers.RedisCluster","msg":"Creating new cluster..."}
{"level":"info","ts":1657693918.6289756,"logger":"controllers.RedisConfig","msg":"Reconciling ACL config for Redis cluster [redis2/dev-rdc]"}
{"level":"info","ts":1657693918.6290882,"logger":"controllers.RedisConfig","msg":"Computed hash: 31328a17085c7c60bb79fa58db21fdeafaceb254244aa1bfe27a3b576fffda89"}
{"level":"info","ts":1657693918.7617204,"logger":"controllers.RedisCluster","msg":"Waiting for pod network interfaces..."}
panic: non-positive interval for NewTicker
goroutine 337 [running]:
time.NewTicker(0x0, 0xc0009a33b0)
	/usr/local/go/src/time/tick.go:24 +0x151
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc000022780, 0x0, 0x0, 0xc000022720)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:574 +0x85
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:571 +0x8c_

flow 2:

_http server started on [::]:8080
I0713 06:30:01.518862       1 request.go:621] Throttling request took 1.034860593s, request: GET:https://172.20.0.1:443/apis/policy/v1beta1?timeout=32s
{"level":"info","ts":1657693802.2733538,"logger":"setup","msg":"Loaded config: {Times:{SyncCheckInterval:0s SyncCheckTimeout:0s SleepDuringTablesAlignProcess:0s ClusterCreateInterval:0s ClusterCreateTimeout:0s ACLFilePropagationDuration:0s ACLFileLoadDuration:0s PodReadyCheckInterval:0s PodReadyCheckTimeout:0s PodNetworkCheckInterval:0s PodNetworkCheckTimeout:0s PodDeleteCheckInterval:0s PodDeleteCheckTimeout:0s RedisPingCheckInterval:0s RedisPingCheckTimeout:0s RedisClusterReplicationCheckInterval:0s RedisClusterReplicationCheckTimeout:0s RedisClusterMeetCheckInterval:0s RedisClusterMeetCheckTimeout:0s RedisManualFailoverCheckInterval:0s RedisManualFailoverCheckTimeout:0s RedisAutoFailoverCheckInterval:0s RedisAutoFailoverCheckTimeout:0s RedisNodesAgreeAboutSlotsConfigTimeout:0s RedisNodesAgreeAboutSlotsConfigCheckInterval:0s RedisRemoveNodeCheckInterval:0s RedisRemoveNodeTimeout:0s WaitForRedisLoadDataSetInMemoryCheckInterval:0s WaitForRedisLoadDataSetInMemoryTimeout:0s SleepIfForgetNodeFails:0s} Thresholds:{SyncMatchThreshold:0 MaxToleratedPodsRecoverAtOnce:0 MaxToleratedPodsUpdateAtOnce:0} Setters:{ExposeSensitiveEntryPoints:false}}"}
{"level":"info","ts":1657693802.2735856,"logger":"setup","msg":"starting manager"}
I0713 06:30:02.275067       1 leaderelection.go:242] attempting to acquire leader lease  redis1/1747e98e.payu.com...
I0713 06:30:22.968515       1 leaderelection.go:252] successfully acquired lease redis1/1747e98e.payu.com
{"level":"info","ts":1657693823.0696962,"logger":"controllers.RedisConfig","msg":"Reconciling operator config for [redis1/redis-cache-redis-operator]"}
{"level":"info","ts":1657693823.0699034,"logger":"controllers.RedisConfig","msg":"Triggered config reload for [redis1/redis-cache-redis-operator]"}
{"level":"info","ts":1657693823.0697489,"logger":"controllers.RedisCluster","msg":"Clear all cluster pods..."}
{"level":"info","ts":1657693823.0699558,"logger":"controllers.RedisCluster","msg":"Clear cluster state map..."}
{"level":"info","ts":1657693823.0699582,"logger":"controllers.RedisConfig","msg":"Reconciling ACL config for Redis cluster [redis1/dev-rdc]"}
{"level":"info","ts":1657693823.0699835,"logger":"controllers.RedisCluster","msg":"Handling initializing cluster..."}
{"level":"info","ts":1657693823.0699942,"logger":"controllers.RedisCluster","msg":"Creating new cluster..."}
{"level":"info","ts":1657693823.0700803,"logger":"controllers.RedisConfig","msg":"Computed hash: 31328a17085c7c60bb79fa58db21fdeafaceb254244aa1bfe27a3b576fffda89"}
{"level":"info","ts":1657693823.1783972,"logger":"controllers.RedisCluster","msg":"Waiting for pod network interfaces..."}
{"level":"error","ts":1657693823.1787682,"logger":"controllers.RedisCluster","msg":"Handling error","error":"timed out waiting for the condition","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/PayU/redis-operator/controllers.(*RedisClusterReconciler).Reconcile\n\t/workspace/controllers/rediscluster_controller.go:139\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:244\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
panic: non-positive interval for NewTicker
goroutine 319 [running]:
time.NewTicker(0x0, 0x159d720)
	/usr/local/go/src/time/tick.go:24 +0x151
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc0004f08a0, 0x0, 0x0, 0xc0004f0840)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:574 +0x85
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:571 +0x8c_

**Comment by doronl** [comment]
@voltbit @NataliAharoniPayu any suggestions?

**Comment by NataliAharoniPayu** [comment]
Hi @doronl , thanks for letting us know regard this issue.
I assume that this issue has many more log lines, one of them should relate the actual line in code that 'started' the mess, it can be detected by the path it uses (it will contain name of component from the project, like *controllers.RedisCluster for example), it is good idea to search it in the log and reflect it here, it will help us to understand and address the issue better.
I suspect this issue is related to one of two scenarios, both worth to be understood to know how to manage the case:
1. Lack of resources (k8s worker nodes) in the cluster you are trying to deploy.
The operator uses hard anti affinity rules both between leader pods and both between leader and followers pods, it means each pod will try to claim worker node of its own. If there is a lack of resources the pod won't be scheduled and won't receive ip address, which will lead the operator to time out while waiting.
We updated the labels that controls this rules to a non-broken version, so this hard rules takes part now and actually works (in the last version it wasn't enforced good enough, so different pods could be scheduled on the same workers).
Notes:
* The rules can be configured in the code to be soft instead of enforced
* We address this issue with a dedicated section in our wiki - [link](https://github.com/PayU/redis-operator/wiki/Design-and-infrastructure)
* Any case, this should not trigger an exception, when we produced this issue on our systems, the operator was able to continue to run without crushing over exception that gets thrown, so it is a case that we are curious to explore if you could send us the log parts that mentions the problematic code parts in the operator.

2. It can be an issue that regards inability to parse the file operator.conf properly.
The operator attempts to look for mounted file operator.conf and rely on its values as the dictating configuration (among the rest timers that determines timeouts of poll-immediate loops).
If the flow of using the file fails, the operator failing-over and use controllers/config.go which is getting translated to a config map that is getting deployed by the operator (redis-operator-config).
The 'default' flow of using the .conf file might be bugged, so i suggest to try to see if commenting out the code part that make use the .conf file works better as the operator should rely the config map when it will happen.

**Comment by NataliAharoniPayu** [comment]
@doronl it is good point we should have added it to change list & trouble shooting section for managing the upgrade.
It will be added now
